# Generated by Django 2.1 on 2018-08-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hobies',
        ),
        migrations.RemoveField(
            model_name='student',
            name='majors',
        ),
        migrations.AddField(
            model_name='hobi',
            name='hobies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobies', to='api_user.Student'),
        ),
        migrations.AddField(
            model_name='major',
            name='majors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major', to='api_user.Student'),
        ),
    ]
